const pair=(en,pl,detailEn,detailPl)=>({en,pl,detailEn,detailPl});
const node=(id,x,y,copy,kind='process')=>({id,x,y,kind,...copy});
const edge=(from,to,kind='process')=>({from,to,kind});
export function viewerModel(slug,lang){
 const models={
  'systems-process-mapping':{type:'map',title:['System map','Mapa systemu'],nodes:[
   node('crm',95,70,pair('CRM','CRM','Customer and order records feed the order flow. If CRM is unavailable, new orders may need to wait or follow an agreed fallback.','Dane klientów i zamówień zasilają realizację. Niedostępność CRM może zatrzymać nowe zamówienia lub wymagać uzgodnionej ścieżki zastępczej.'),'data'),
   node('orders',320,70,pair('Order flow','Zamówienia','Connects customer records, fulfilment and billing. A failure here can affect several downstream teams.','Łączy dane klienta, realizację i rozliczenia. Awaria może wpłynąć na kilka kolejnych zespołów.')),
   node('delivery',545,70,pair('Delivery','Realizacja','Needs a validated order. A manual handoff can keep work moving, provided ownership and reconciliation are clear.','Potrzebuje zweryfikowanego zamówienia. Ręczne przekazanie może podtrzymać pracę, jeśli ustalimy odpowiedzialność i późniejsze uzgodnienie danych.')),
   node('support',95,245,pair('Support','Wsparcie','Uses customer history to answer enquiries. Missing records can increase manual work and response time.','Korzysta z historii klienta. Brak danych może zwiększyć ręczną pracę i czas odpowiedzi.')),
   node('billing',320,245,pair('Billing','Rozliczenia','Depends on order status and customer details. Incorrect inputs can create incorrect invoices.','Zależy od statusu zamówienia i danych klienta. Błędne dane mogą powodować błędy na fakturach.'),'risk'),
   node('finance',545,245,pair('Finance','Finanse','Consumes billing records. Recovery needs reconciliation so delayed or repeated updates do not produce duplicate work.','Odbiera dane rozliczeniowe. Po awarii trzeba uzgodnić rekordy, aby opóźnione lub powtórzone aktualizacje nie tworzyły podwójnej pracy.'),'data')
  ],edges:[edge('crm','orders','data'),edge('crm','support','data'),edge('orders','delivery'),edge('orders','billing','risk'),edge('billing','finance','data')]},
  'workflows-pipelines':{type:'pipeline',title:['Workflow & pipeline','Workflow i pipeline'],nodes:[
   node('intake',95,70,pair('Intake','Przyjęcie','Input: request and source files. Output: an identified task with an owner. Missing information returns to the requester.','Wejście: zgłoszenie i pliki. Wyjście: rozpoznane zadanie z właścicielem. Braki wracają do zgłaszającego.')),
   node('prepare',320,70,pair('Prepare','Przygotowanie','Input: source material. Output: validated inputs for production. Repeated copying is a candidate for automation after the rules are clear.','Wejście: materiały źródłowe. Wyjście: zweryfikowane dane do produkcji. Kopiowanie można zautomatyzować po ustaleniu reguł.')),
   node('review',545,70,pair('Review · bottleneck','Ocena · wąskie gardło','A limited review capacity creates a queue in this example. Automation can prepare evidence, but an accountable person still approves the result.','W tym przykładzie ograniczona dostępność osoby oceniającej tworzy kolejkę. Automatyzacja może przygotować informacje, ale za akceptację nadal odpowiada człowiek.'),'risk'),
   node('handoff',545,245,pair('Handoff','Przekazanie','Input: approved work. Output: the next team receives files, status and responsibility together. Partial delivery needs a visible exception path.','Wejście: zaakceptowana praca. Wyjście: kolejny zespół otrzymuje pliki, status i odpowiedzialność. Niepełne przekazanie wymaga obsługi wyjątku.')),
   node('deliver',320,245,pair('Deliver','Dostarczenie','The output is delivered with its version and destination. Failed delivery should be visible and recoverable.','Rezultat jest dostarczany z numerem wersji i adresem odbiorcy. Nieudane dostarczenie musi być widoczne i możliwe do wznowienia.')),
   node('validate',95,245,pair('Validate','Weryfikacja','Check the received output against the request. Record corrections and update the understanding of the workflow.','Sprawdź otrzymany wynik względem zgłoszenia. Zapisz poprawki i zaktualizuj obraz workflow.'))
  ],edges:[edge('intake','prepare'),edge('prepare','review'),edge('review','handoff','risk'),edge('handoff','deliver'),edge('deliver','validate')]},
  'automation-ai':{type:'decision',title:['Automation decision flow','Decyzje w automatyzacji'],nodes:[
   node('input',95,70,pair('Input','Dane wejściowe','Validate the source, permissions and quality. Missing or invalid inputs need an exception path before any automation proceeds.','Sprawdź źródło, uprawnienia i jakość. Brakujące lub błędne dane wymagają ścieżki wyjątku przed uruchomieniem automatyzacji.'),'data'),
   node('process',320,70,pair('Process','Przetwarzanie','Prepare and classify the task. The nature of the work determines which decision path is appropriate.','Przygotuj i sklasyfikuj zadanie. Charakter pracy decyduje o wyborze właściwej ścieżki.')),
   node('rules',95,245,pair('Deterministic','Reguły deterministyczne','Use explicit rules for repeatable operations such as validation or calculations. Undefined cases return to a person instead of being guessed.','Jawne reguły służą powtarzalnym operacjom, np. walidacji lub obliczeniom. Niezdefiniowane przypadki wracają do człowieka.')),
   node('ai',320,245,pair('AI-assisted','Wsparcie AI','AI can help extract or analyse complex information. Results need checks appropriate to the risk; AI output is not automatically an approved decision.','AI może wspierać analizę lub odczyt złożonych informacji. Wynik wymaga kontroli dopasowanej do ryzyka i nie jest automatycznie zatwierdzoną decyzją.'),'data'),
   node('human',545,245,pair('Human review','Ocena człowieka','A person resolves ambiguity, reviews exceptions and remains responsible for consequential decisions. The review criteria should be explicit.','Człowiek rozstrzyga niejasności, ocenia wyjątki i odpowiada za ważne decyzje. Kryteria oceny powinny być jawne.'),'risk'),
   node('output',545,70,pair('Output & monitoring','Wynik i monitoring','Deliver the result, record its origin and monitor failures. Incorrect outputs need a way to stop, correct and recover the process.','Dostarcz wynik, zapisz jego pochodzenie i monitoruj błędy. Niepoprawny wynik wymaga możliwości zatrzymania, poprawy i wznowienia procesu.'))
  ],edges:[edge('input','process'),edge('process','rules'),edge('process','ai','data'),edge('process','human','risk'),edge('rules','output'),edge('ai','human','risk'),edge('human','output')]},
  'technology-audit':{type:'audit',title:['Audit layers','Warstwy audytu'],nodes:[
   node('people',95,70,pair('People','Ludzie','Who does the work, who makes decisions, and who owns the result? Interviews reveal workarounds that documentation can miss.','Kto wykonuje pracę, podejmuje decyzje i odpowiada za wynik? Rozmowy ujawniają obejścia niewidoczne w dokumentacji.')),
   node('process',320,70,pair('Process','Proces','Trace handoffs, queues, exceptions and repeated steps. Compare the documented process with how work actually happens.','Sprawdź przekazania, kolejki, wyjątki i powtarzane kroki. Porównaj dokumentację z rzeczywistym sposobem pracy.')),
   node('systems',545,70,pair('Systems','Systemy','Inventory software, integrations, permissions and ownership. Check where a local workaround has become a critical dependency.','Zinwentaryzuj programy, integracje, uprawnienia i odpowiedzialność. Sprawdź, gdzie lokalne obejście stało się krytyczną zależnością.')),
   node('data',95,245,pair('Data','Dane','Examine sources, quality, duplication, access and transformations. Record which evidence supports a finding.','Zbadaj źródła, jakość, duplikaty, dostęp i przetwarzanie. Zapisz dowody wspierające ustalenia.'),'data'),
   node('infra',320,245,pair('Infrastructure','Infrastruktura','Review capacity, connectivity, access, backups and recovery arrangements within the agreed scope.','Oceń wydajność, połączenia, dostęp, kopie i odtwarzanie działania w uzgodnionym zakresie.')),
   node('risk',545,245,pair('Risk & constraints','Ryzyko i ograniczenia','Connect technical findings to business consequences, costs and constraints. Distinguish verified findings from assumptions.','Połącz ustalenia techniczne ze skutkami biznesowymi, kosztami i ograniczeniami. Oddziel fakty od założeń.'),'risk')
  ],edges:[edge('people','process'),edge('process','systems'),edge('systems','data','data'),edge('data','infra'),edge('infra','risk','risk')]},
  'implementation-support':{type:'production',title:['Production responsibilities','Odpowiedzialność w produkcji'],nodes:[
   node('app',95,70,pair('Application','Aplikacja','Define expected behaviour and acceptance checks. A successful demo does not establish operational readiness.','Określ oczekiwane działanie i kryteria odbioru. Udane demo nie potwierdza gotowości operacyjnej.')),
   node('integration',320,70,pair('Integration','Integracja','Validate contracts between systems, permissions and failure paths. Partially completed operations must be detectable.','Sprawdź ustalenia między systemami, uprawnienia i obsługę błędów. Częściowe wykonanie musi być wykrywalne.')),
   node('monitoring',545,70,pair('Monitoring','Monitoring','Make failures visible to someone who can respond. An alert without an owner is not an incident response process.','Zapewnij widoczność błędów osobie mogącej zareagować. Alert bez właściciela nie jest procesem obsługi awarii.'),'risk'),
   node('recovery',545,245,pair('Recovery','Odtwarzanie','Agree how to restore service and reconcile work after interruption. Test the recovery path where the scope requires it.','Ustal powrót do działania i uzgodnienie pracy po przerwie. Testuj odtwarzanie, gdy wymaga tego zakres.')),
   node('ownership',320,245,pair('Ownership','Odpowiedzialność','Name the people responsible for operating, maintaining and changing the solution. Handover includes the information they need.','Wskaż osoby odpowiedzialne za działanie, utrzymanie i zmiany. Przekazanie obejmuje potrzebne im informacje.'))
  ],edges:[edge('app','integration'),edge('integration','monitoring','risk'),edge('monitoring','recovery','risk'),edge('recovery','ownership')]},
  'technology-consulting':{type:'architecture',title:['Current / proposed','Obecnie / propozycja'],nodes:[
   node('team',95,70,pair('Team','Zespół','Start with the people and the business goal. A proposed architecture must fit the way the team can operate it.','Zacznij od ludzi i celu biznesowego. Proponowana architektura musi pasować do możliwości zespołu.')),
   node('tools',320,70,pair('Tools','Narzędzia','The current example relies on several direct handoffs. A proposed design introduces a clearer shared integration boundary.','Obecny przykład opiera się na wielu bezpośrednich przekazaniach. Propozycja wprowadza czytelniejszą wspólną granicę integracji.')),
   node('data',545,70,pair('Data','Dane','Clarify the authoritative source before connecting more tools. A shared integration does not solve poor data quality by itself.','Ustal wiarygodne źródło przed podłączeniem kolejnych narzędzi. Wspólna integracja sama nie rozwiązuje problemu jakości danych.'),'data'),
   node('integration',320,245,pair('Integration','Integracja','An explicit integration layer can centralise validation and handoffs. It also creates a dependency that needs monitoring and recovery.','Jawna warstwa integracji może porządkować walidację i przekazania. Tworzy też zależność wymagającą monitoringu i odtwarzania.')),
   node('operations',95,245,pair('Operations','Operacje','Evaluate whether the proposal reduces unnecessary manual work without introducing unacceptable operational risk.','Oceń, czy propozycja ogranicza zbędną ręczną pracę bez wprowadzania nieakceptowalnego ryzyka.')),
   node('reporting',545,245,pair('Reporting','Raportowanie','A simpler diagram is not proof of a better system. Validate the proposal against goals, costs and constraints.','Prostszy diagram nie dowodzi lepszego systemu. Sprawdź propozycję względem celów, kosztów i ograniczeń.'))
  ],edges:[edge('team','tools'),edge('team','operations'),edge('tools','data','data'),edge('tools','operations'),edge('data','reporting','data'),edge('operations','reporting')],proposed:[edge('team','tools'),edge('tools','integration'),edge('data','integration','data'),edge('integration','operations'),edge('integration','reporting','data')]}
 };
 const model=models[slug];if(!model)return null;
 return {...model,title:model.title[lang==='pl'?1:0],nodes:model.nodes.map(n=>({...n,label:n[lang],detail:n[lang==='pl'?'detailPl':'detailEn']}))};
}
